# Generates src/gfx_shaders.h and src/gfx_shaders.cpp from the HLSL sources
# in src/shaders. The GPU backend embeds the compiled bytecode so the build
# has no shader-compilation step (robust across the MSVC and CMake builds).
#
# Usage:  powershell -ExecutionPolicy Bypass -File tools\gen_shaders.ps1
#
# Requires DXC. It is looked up in the Vulkan SDK first, then in the Windows
# Kits. Both produce DXIL (D3D12) and SPIR-V (Vulkan) per shader; the SPIR-V
# is compiled with -fvk-use-dx-layout so HLSL register spaces map to the
# descriptor sets SDL_GPU expects (see the comments in the .hlsl files).

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$srcDir = Join-Path $root 'src'
$shaderDir = Join-Path $srcDir 'shaders'
$outHeader = Join-Path $srcDir 'gfx_shaders.h'
$outCpp = Join-Path $srcDir 'gfx_shaders.cpp'
$work = Join-Path $root '.shaderbuild'

$dxc = 'G:\VulkanSDK\Bin\dxc.exe'
if (-not (Test-Path $dxc)) {
    $dxc = Get-ChildItem 'C:\Program Files (x86)\Windows Kits\10\bin' -Recurse -Filter dxc.exe -ErrorAction SilentlyContinue |
        Sort-Object FullName -Descending | Select-Object -First 1 -ExpandProperty FullName
}
if (-not $dxc -or -not (Test-Path $dxc)) { throw 'dxc.exe not found (Vulkan SDK or Windows Kits)' }

New-Item -ItemType Directory -Path $work -Force | Out-Null

# name, dxc profile, source file, stage
$stages = @(
    @{ var = 'gTLVertex';        profile = 'vs_6_0'; src = 'tl_vertex.hlsl' },
    @{ var = 'gTLTexturedFrag';  profile = 'ps_6_0'; src = 'tl_textured_fragment.hlsl' },
    @{ var = 'gTLUntexturedFrag'; profile = 'ps_6_0'; src = 'tl_untextured_fragment.hlsl' }
)

function New-ByteArray($name, $path) {
    $bytes = [System.IO.File]::ReadAllBytes($path)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("    // $([System.IO.Path]::GetFileName($path)) ($($bytes.Length) bytes)")
    [void]$sb.AppendLine("    static constexpr uint8_t $name[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 12) {
        $row = $bytes[$i..([Math]::Min($i + 11, $bytes.Length - 1))]
        [void]$sb.Append('        ')
        [void]$sb.Append(($row | ForEach-Object { '0x{0:X2},' -f $_ }) -join ' ')
        [void]$sb.AppendLine()
    }
    [void]$sb.AppendLine('    };')
    return $sb.ToString()
}

$dxilBlocks = New-Object System.Collections.Generic.List[string]
$spirvBlocks = New-Object System.Collections.Generic.List[string]
foreach ($s in $stages) {
    $src = Join-Path $shaderDir $s.src
    $dxil = Join-Path $work ($s.src + '.dxil')
    $spv = Join-Path $work ($s.src + '.spv')
    & $dxc -nologo -T $s.profile -E main -Zpr -Fo $dxil $src | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "dxc failed for $($s.src) (DXIL)" }
    & $dxc -nologo -T $s.profile -E main -spirv -fvk-use-dx-layout -Zpr -Fo $spv $src | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "dxc failed for $($s.src) (SPIR-V)" }
    $dxilBlocks.Add((New-ByteArray ($s.var + 'DxilData') $dxil))
    $spirvBlocks.Add((New-ByteArray ($s.var + 'SpirvData') $spv))
}

# ---- header ----
$header = @"
#pragma once
// Generated by tools\gen_shaders.ps1 - do not edit by hand.
// Embedded HLSL shader bytecode (compiled to DXIL and SPIR-V with DXC) for
// the GPU backend draw pipeline. See src\shaders\*.hlsl for the sources.
#include <cstdint>

namespace openre::gfx
{
    extern const uint8_t* gTLVertexDxil;
    extern const uint8_t* gTLVertexSpirv;
    extern const uint8_t* gTLTexturedFragDxil;
    extern const uint8_t* gTLTexturedFragSpirv;
    extern const uint8_t* gTLUntexturedFragDxil;
    extern const uint8_t* gTLUntexturedFragSpirv;

    extern const uint32_t gTLVertexDxilSize;
    extern const uint32_t gTLVertexSpirvSize;
    extern const uint32_t gTLTexturedFragDxilSize;
    extern const uint32_t gTLTexturedFragSpirvSize;
    extern const uint32_t gTLUntexturedFragDxilSize;
    extern const uint32_t gTLUntexturedFragSpirvSize;
}
"@
Set-Content -Path $outHeader -Value $header -Encoding ASCII

# ---- cpp ----
$cpp = New-Object System.Text.StringBuilder
[void]$cpp.AppendLine('#include "gfx_shaders.h"')
[void]$cpp.AppendLine()
[void]$cpp.AppendLine('namespace openre::gfx')
[void]$cpp.AppendLine('{')
foreach ($b in $dxilBlocks) { [void]$cpp.AppendLine($b) }
foreach ($b in $spirvBlocks) { [void]$cpp.AppendLine($b) }
[void]$cpp.AppendLine(@'
    const uint8_t* gTLVertexDxil = gTLVertexDxilData;
    const uint8_t* gTLVertexSpirv = gTLVertexSpirvData;
    const uint8_t* gTLTexturedFragDxil = gTLTexturedFragDxilData;
    const uint8_t* gTLTexturedFragSpirv = gTLTexturedFragSpirvData;
    const uint8_t* gTLUntexturedFragDxil = gTLUntexturedFragDxilData;
    const uint8_t* gTLUntexturedFragSpirv = gTLUntexturedFragSpirvData;

    const uint32_t gTLVertexDxilSize = sizeof(gTLVertexDxilData);
    const uint32_t gTLVertexSpirvSize = sizeof(gTLVertexSpirvData);
    const uint32_t gTLTexturedFragDxilSize = sizeof(gTLTexturedFragDxilData);
    const uint32_t gTLTexturedFragSpirvSize = sizeof(gTLTexturedFragSpirvData);
    const uint32_t gTLUntexturedFragDxilSize = sizeof(gTLUntexturedFragDxilData);
    const uint32_t gTLUntexturedFragSpirvSize = sizeof(gTLUntexturedFragSpirvData);
}
'@)
Set-Content -Path $outCpp -Value $cpp.ToString() -Encoding ASCII

Remove-Item -Recurse -Force $work
Write-Host "Generated $outHeader and $outCpp"
