# Generates the embedded shader bytecode sections in src\system_gpu.h and
# src\system_gpu.cpp from the HLSL sources in src\shaders. The GPU backend
# (system_gpu.cpp) embeds the compiled bytecode so the build has no
# shader-compilation step (robust across the MSVC and CMake builds).
#
# Usage:  powershell -ExecutionPolicy Bypass -File tools\gen_shaders.ps1
#
# The generated sections are delimited by
#   // ====BEGIN GENERATED: shader bytecode (tools\gen_shaders.ps1)====
#   // ====END GENERATED: shader bytecode (tools\gen_shaders.ps1)====
# markers and are replaced in place (the shader data lives in system_gpu
# since the GPU stack was merged into a single translation unit).
#
# Requires DXC. It is looked up in the Vulkan SDK first, then in the Windows
# Kits. Both produce DXIL (D3D12) and SPIR-V (Vulkan) per shader; the SPIR-V
# is compiled with -fvk-use-dx-layout so HLSL register spaces map to the
# descriptor sets SDL_GPU expects (see the comments in the .hlsl files).

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$srcDir = Join-Path $root 'src'
$shaderDir = Join-Path $srcDir 'shaders'
$outHeader = Join-Path $srcDir 'system_gpu.h'
$outCpp = Join-Path $srcDir 'system_gpu.cpp'
$work = Join-Path $root '.shaderbuild'

$beginMarker = '// ====BEGIN GENERATED: shader bytecode (tools\gen_shaders.ps1)===='
$endMarker = '// ====END GENERATED: shader bytecode (tools\gen_shaders.ps1)===='

$dxc = 'G:\VulkanSDK\Bin\dxc.exe'
if (-not (Test-Path $dxc)) {
    $dxc = Get-ChildItem 'C:\Program Files (x86)\Windows Kits\10\bin' -Recurse -Filter dxc.exe -ErrorAction SilentlyContinue |
        Sort-Object FullName -Descending | Select-Object -First 1 -ExpandProperty FullName
}
if (-not $dxc -or -not (Test-Path $dxc)) { throw 'dxc.exe not found (Vulkan SDK or Windows Kits)' }

New-Item -ItemType Directory -Path $work -Force | Out-Null

# name, dxc profile, source file, stage
$stages = @(
    @{ var = 'gTLVertex';        profile = 'vs_6_0'; src = 'tl_vertex.hlsl' },
    @{ var = 'gTLTexturedFrag';  profile = 'ps_6_0'; src = 'tl_textured_fragment.hlsl' },
    @{ var = 'gTLUntexturedFrag'; profile = 'ps_6_0'; src = 'tl_untextured_fragment.hlsl' }
)

function New-ByteArray($name, $path) {
    $bytes = [System.IO.File]::ReadAllBytes($path)
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("    // $([System.IO.Path]::GetFileName($path)) ($($bytes.Length) bytes)")
    [void]$sb.AppendLine("    static constexpr uint8_t $name[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 12) {
        $row = $bytes[$i..([Math]::Min($i + 11, $bytes.Length - 1))]
        [void]$sb.Append('        ')
        [void]$sb.Append(($row | ForEach-Object { '0x{0:X2},' -f $_ }) -join ' ')
        [void]$sb.AppendLine()
    }
    [void]$sb.AppendLine('    };')
    return $sb.ToString()
}

$dxilBlocks = New-Object System.Collections.Generic.List[string]
$spirvBlocks = New-Object System.Collections.Generic.List[string]
foreach ($s in $stages) {
    $src = Join-Path $shaderDir $s.src
    $dxil = Join-Path $work ($s.src + '.dxil')
    $spv = Join-Path $work ($s.src + '.spv')
    & $dxc -nologo -T $s.profile -E main -Zpr -Fo $dxil $src | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "dxc failed for $($s.src) (DXIL)" }
    & $dxc -nologo -T $s.profile -E main -spirv -fvk-use-dx-layout -Zpr -Fo $spv $src | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "dxc failed for $($s.src) (SPIR-V)" }
    $dxilBlocks.Add((New-ByteArray ($s.var + 'DxilData') $dxil))
    $spirvBlocks.Add((New-ByteArray ($s.var + 'SpirvData') $spv))
}

# ---- header section ----
$headerSection = @"
$beginMarker
// Generated by tools\gen_shaders.ps1 - do not edit by hand.
// Embedded HLSL shader bytecode (compiled to DXIL and SPIR-V with DXC) for
// the GPU backend draw pipeline. See src\shaders\*.hlsl for the sources.
#include <cstdint>

namespace openre::gfx
{
    extern const uint8_t* gTLVertexDxil;
    extern const uint8_t* gTLVertexSpirv;
    extern const uint8_t* gTLTexturedFragDxil;
    extern const uint8_t* gTLTexturedFragSpirv;
    extern const uint8_t* gTLUntexturedFragDxil;
    extern const uint8_t* gTLUntexturedFragSpirv;

    extern const uint32_t gTLVertexDxilSize;
    extern const uint32_t gTLVertexSpirvSize;
    extern const uint32_t gTLTexturedFragDxilSize;
    extern const uint32_t gTLTexturedFragSpirvSize;
    extern const uint32_t gTLUntexturedFragDxilSize;
    extern const uint32_t gTLUntexturedFragSpirvSize;
}
$endMarker
"@

# ---- cpp section ----
$cpp = New-Object System.Text.StringBuilder
[void]$cpp.AppendLine($beginMarker)
[void]$cpp.AppendLine('namespace openre::gfx')
[void]$cpp.AppendLine('{')
foreach ($b in $dxilBlocks) { [void]$cpp.AppendLine($b) }
foreach ($b in $spirvBlocks) { [void]$cpp.AppendLine($b) }
[void]$cpp.AppendLine(@'
    const uint8_t* gTLVertexDxil = gTLVertexDxilData;
    const uint8_t* gTLVertexSpirv = gTLVertexSpirvData;
    const uint8_t* gTLTexturedFragDxil = gTLTexturedFragDxilData;
    const uint8_t* gTLTexturedFragSpirv = gTLTexturedFragSpirvData;
    const uint8_t* gTLUntexturedFragDxil = gTLUntexturedFragDxilData;
    const uint8_t* gTLUntexturedFragSpirv = gTLUntexturedFragSpirvData;

    const uint32_t gTLVertexDxilSize = sizeof(gTLVertexDxilData);
    const uint32_t gTLVertexSpirvSize = sizeof(gTLVertexSpirvData);
    const uint32_t gTLTexturedFragDxilSize = sizeof(gTLTexturedFragDxilData);
    const uint32_t gTLTexturedFragSpirvSize = sizeof(gTLTexturedFragSpirvData);
    const uint32_t gTLUntexturedFragDxilSize = sizeof(gTLUntexturedFragDxilData);
    const uint32_t gTLUntexturedFragSpirvSize = sizeof(gTLUntexturedFragSpirvData);
}
'@)
[void]$cpp.AppendLine($endMarker)

# Replaces the marked section in $path with $section, preserving the rest of
# the file byte-for-byte and keeping the section in place. Appends at the end
# (after a blank line) when no marker is present yet.
function Set-GeneratedSection([string]$path, [string]$section) {
    $section = ($section -replace "`r`n", "`n").TrimEnd("`n")
    $text = [System.IO.File]::ReadAllText($path)
    $startIdx = $text.IndexOf($beginMarker)
    if ($startIdx -ge 0) {
        $endIdx = $text.IndexOf($endMarker, $startIdx)
        if ($endIdx -lt 0) { throw "END marker missing in $path" }
        $endIdx += $endMarker.Length
        $text = $text.Remove($startIdx, $endIdx - $startIdx)
        # Collapse the blank line the removed section left behind.
        if ($startIdx -ge 2 -and $text.Substring($startIdx - 2, 2) -eq "`n`n") {
            $text = $text.Remove($startIdx - 1, 1)
            $startIdx--
        }
        $text = $text.Insert($startIdx, $section + "`n")
    }
    else {
        if ($text.Length -gt 0 -and -not $text.EndsWith("`n")) { $text += "`n" }
        if ($text.Length -gt 0 -and -not $text.EndsWith("`n`n")) { $text += "`n" }
        $text += $section + "`n"
    }
    [System.IO.File]::WriteAllText($path, $text, [System.Text.UTF8Encoding]::new($false))
}

Set-GeneratedSection $outHeader $headerSection
Set-GeneratedSection $outCpp $cpp.ToString()

Remove-Item -Recurse -Force $work
Write-Host "Generated shader sections in $outHeader and $outCpp"
