block-beta
  columns 6
  LuaVM1["LuaVM\n<span style='font-size: 0.7em;'>game/RE2</span>"]
  LuaVM2["LuaVM\n<span style='font-size: 0.7em;'>mod/RE2HD</span>"]
  LuaVM3["LuaVM\n<span style='font-size: 0.7em;'>mod/srt</span>"]
  bio2.exe:3
  LuaManager:3
  GameVM["GameVM\n<span style='font-size: 0.7em;'>game/RE2</span>"]
  DoorVM["DoorVM\n<span style='font-size: 0.7em;'>game/RE2/door/D01.DOR</span>"]
  RoomVM["RoomVM\n<span style='font-size: 0.7em;'>game/RE2/room/R100.rdt</span>"]
  block:shell:6
    columns 3
    ShellExtensions ResourceManager Logger
  end
  Shell:6
  SDL3/OpenGL:6
  Windows:3
  Linux:3
