#pragma once
// Generated by tools\gen_shaders.ps1 - do not edit by hand.
// Embedded HLSL shader bytecode (compiled to DXIL and SPIR-V with DXC) for
// the GPU backend draw pipeline. See src\shaders\*.hlsl for the sources.
#include <cstdint>

namespace openre::gfx
{
    extern const uint8_t* gTLVertexDxil;
    extern const uint8_t* gTLVertexSpirv;
    extern const uint8_t* gTLTexturedFragDxil;
    extern const uint8_t* gTLTexturedFragSpirv;
    extern const uint8_t* gTLUntexturedFragDxil;
    extern const uint8_t* gTLUntexturedFragSpirv;

    extern const uint32_t gTLVertexDxilSize;
    extern const uint32_t gTLVertexSpirvSize;
    extern const uint32_t gTLTexturedFragDxilSize;
    extern const uint32_t gTLTexturedFragSpirvSize;
    extern const uint32_t gTLUntexturedFragDxilSize;
    extern const uint32_t gTLUntexturedFragSpirvSize;
}
