#pragma once

namespace openre
{
    enum
    {
        ITEM_TYPE_NONE = 0,
        ITEM_TYPE_KNIFE = 1,
        ITEM_TYPE_HANDGUN_LEON = 2,
        ITEM_TYPE_HANDGUN_CLAIRE = 3,
        ITEM_TYPE_HANDGUN_COLT_SAA = 13,
        ITEM_TYPE_AMMO_HANDGUN = 20,
        ITEM_TYPE_AMMO_SHOTGUN = 21,
        ITEM_TYPE_AMMO_MAGNUM = 22,
        ITEM_TYPE_AMMO_FLAMETHROWER = 23,
        ITEM_TYPE_AMMO_EXPLOSIVE_ROUNDS = 24,
        ITEM_TYPE_AMMO_FLAME_ROUNDS = 25,
        ITEM_TYPE_AMMO_ACID_ROUNDS = 26,
        ITEM_TYPE_AMMO_SMG = 27,
        ITEM_TYPE_AMMO_SPARKSHOT = 28,
        ITEM_TYPE_AMMO_BOWGUN = 29,
        ITEM_TYPE_INK_RIBBON = 30,
        ITEM_TYPE_FIRST_AID_SPRAY = 35,
        ITEM_TYPE_GREEN_HERB = 38,
        ITEM_TYPE_HERB_GGB = 45,
        ITEM_TYPE_LIGHTER = 47,
        ITEM_TYPE_LOCKPICK = 48,
        ITEM_TYPE_PHOTO_SHERRY = 49,
        ITEM_TYPE_PHOTO_ADA = 87,
    };
}
