#pragma once

#include <cstdint>

namespace openre::system::gpu
{
    // The GPU subsystem owner: the SDL_GPU device, the window's swapchain and
    // the guest framebuffer (the offscreen render target the scene is rendered
    // into before being letterboxed into the swapchain).
    //
    // The window is claimed exactly once (at first init()). init() is called
    // eagerly from marni::init (so the ddraw surfaces created by init_all can
    // register against the backend device) and is idempotent, so
    // create_guest_framebuffer/present() may also trigger it safely.

    // Creates the SDL_GPU device and claims the game window on first use.
    // Idempotent; safe to call repeatedly. Returns false on failure.
    bool init();

    // Ensures the guest framebuffer exists at `width` x `height` (the render
    // resolution), re-creating it when the size changes. Returns the underlying
    // SDL_GPUTexture* as void* (SDL stays out of this header), or nullptr on
    // failure. The framebuffer is released by shutdown().
    void* create_guest_framebuffer(int width, int height);

    // True once the GPU device exists (and the window is claimed).
    bool is_initialized();

    // ---- raw SDL_GPU access (SDL-only renderer prototype) ----
    // The SDL-only renderer (SdlGpuRenderer) drives SDL_GPU directly and
    // bypasses the COM-shaped GfxBackend replay path, so it needs the raw
    // device/window/framebuffer objects. Return nullptr/0 until the device
    // has been created (or after shutdown()).
    void* device();            // SDL_GPUDevice*
    void* window();            // SDL_Window*
    void* guest_framebuffer(); // SDL_GPUTexture* (nullptr until create_guest_framebuffer)
    int framebuffer_width();
    int framebuffer_height();
    int swapchain_format();    // SDL_GPUTextureFormat value (SDL stays out of this header)

    // Acquires the swapchain texture and presents the guest framebuffer (the
    // GPU backend replays the frame's draws into it, then letterboxes it into
    // the swapchain). Creates the device on first use.
    void present();

    // Movie frame bridge (Phase 7): the movie player (marni_movie.cpp) captures
    // decoded DirectShow frames and hands them over here; the GPU backend
    // composites the latest frame into the guest framebuffer during present()
    // (after the scene pass and the GDI text overlay), so cutscenes render into
    // the framebuffer with no separate video window. `pixels` is a top-down
    // RGB24 bitmap with `pitch` bytes per row; the backend copies the pixels
    // immediately, so the caller may reuse its buffer. Passing nullptr (or
    // width/height 0) clears the movie overlay. Safe to call before the GPU
    // exists (the frame is then dropped).
    void set_movie_frame(const void* pixels, int width, int height, int pitch);

    // Clears the movie overlay (no movie frame is composited any more).
    void clear_movie_frame();

    // OPENRE_NO_D3D movie frame readout for the SDL-only renderer: returns the
    // latest captured frame (top-down RGB24, `pitch` bytes/row) or nullptr when
    // none is available, filling width/height/pitch. Clears the "new frame"
    // flag so flip() only re-uploads when a fresh frame arrived.
    const void* movie_frame(int& width, int& height, int& pitch);

    // True while a movie frame is set (composite even without a fresh frame).
    bool movie_frame_valid();

    // True when a fresh movie frame arrived since the last movie_frame() read.
    bool movie_frame_new();

    // Releases the guest framebuffer, unclaims the window and destroys the
    // device. Idempotent.
    void shutdown();
}

// ====BEGIN GENERATED: shader bytecode (tools\gen_shaders.ps1)====
// Generated by tools\gen_shaders.ps1 - do not edit by hand.
// Embedded HLSL shader bytecode (compiled to DXIL and SPIR-V with DXC) for
// the GPU backend draw pipeline. See src\shaders\*.hlsl for the sources.
#include <cstdint>

namespace openre::gfx
{
    extern const uint8_t* gTLVertexDxil;
    extern const uint8_t* gTLVertexSpirv;
    extern const uint8_t* gTLTexturedFragDxil;
    extern const uint8_t* gTLTexturedFragSpirv;
    extern const uint8_t* gTLUntexturedFragDxil;
    extern const uint8_t* gTLUntexturedFragSpirv;

    extern const uint32_t gTLVertexDxilSize;
    extern const uint32_t gTLVertexSpirvSize;
    extern const uint32_t gTLTexturedFragDxilSize;
    extern const uint32_t gTLTexturedFragSpirvSize;
    extern const uint32_t gTLUntexturedFragDxilSize;
    extern const uint32_t gTLUntexturedFragSpirvSize;
}
// ====END GENERATED: shader bytecode (tools\gen_shaders.ps1)====
